config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    collection { post :import }
    member do
      get 'index_working_users'
      post 'index_working_users'
      get 'edit_overtime_req'
      patch 'update_overtime_req'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end
  
  resources :bases
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
    # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { in: 5..100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
  validates :employee_number, presence: true, length: { minimum: 3 }
  validates :affiliation, length: { in: 2..30 }, allow_blank: true
  
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      user = new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!
    end
  end  
  
  # def self.import(file)
  #   columns = %i(name, email, affiliation, employee_number)
  #   CSV.foreach(file.path, headers: true) do |row|
  #     values = []
  #     values << [ row[0], row[1], row[2], row[3]]
  #     User.import columns, values
  #   end
  # end
  
  # def self.import(file)
  #   list = []
  #   CSV.foreach(file.path, headers: true) do |row|
  #   list.push( name: row["name"],
  #           email: row["email"],
  #           affiliation: row["affiliation"],
  #           employee_number: row["employee_number"]
  #   )      
  #   end
  #     User.create(list)
  # end
  
    # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number",  "uid", "basic_work_time",
    "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  
    # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, 
                                  :edit_overtime_req, :update_basic_info,
                                  :edit_basic_info, :update_basic_info]
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info]
  before_action :admin_or_current_user, only: [:show, :edit, :update, :edit_basic_info, :update_basic_info]
  # before_action :correct_user, only: [:edit, :update]
  before_action :set_one_month, only: :show

  def index
     @users = User.paginate(page: params[:page], per_page: 10).order('id ASC')
  end

  def index_working_users
    @working_users = []
      User.all.each do |user|
        if user.attendances.any?{|a| (Date.today && !a.started_at.blank? && a.finished_at.blank?)}
          @working_users.push(user)
        end
      end
  end

  def import
    if params[:file].blank?
      flash[:warning] = "CSVファイルが選択されていません。"
      redirect_to users_url
    else
      User.import(params[:file])
      flash[:success] = "ユーザー情報をインポートしました。"
      redirect_to users_url
    end
  end

  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規ユーザーを作成しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to users_url
    else
      render :index    
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_overtime_req
  end

  def update_overtime_req
  end

  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :password_confirmation,
                                   :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end

    def basic_info_params
      params.require(:user).permit(:basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_overtime_req.erb
<!--モーダルウィンドウ　表示確認のための、仮の記述-->

<div class="modal-dialog" role="document">
  <div class="modal-content">
    <%= form_with(model: @user, remote: true) do |f| %>
    <%= render partial: 'shared/error_messages', locals: {obj: @user} %>
 
      
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">【残業申請】</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    
      <div class="modal-body">
        <div class="form-group field">
         <%= f.label :name, class:"form-control-label"%>
         <%= f.text_field :name, id: :user_name, class:"form-control" %>
        </div>
      </div>
      
      <div class="modal-footer actions">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        <%= f.submit class:"btn btn-primary"%>
      </div>
      
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render partial: 'shared/error_messages', locals: {obj: @user} %>

   <%= f.label :name, class: "label-form" %>
   <%= f.text_field :name, class:  "form-control"%>
  
   <%= f.label :email, class: "label-form" %>
   <%= f.email_field :email, class:  "form-control"%>
   
   <%= f.label :affiliation, class: "label-form" %>
   <%= f.text_field :affiliation, class:  "form-control"%>
  
   <%= f.label :password, class: "label-form" %>
   <%= f.password_field :password, class:  "form-control"%>
  
   <%= f.label :password_confirmation, class: "label-form" %>
   <%= f.password_field :password_confirmation, class:  "form-control"%>
   
   <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-form" %>
<% end %>

app/views/users/_user.html.erb
<ul>
  <h4><%= link_to user.name, user_path(user) %></h4>
  <div>
   | <%= link_to "削除", user, method: :delete, data: 
     { confirm: "本当に削除してもよろしいですか？" }, class:"btn btn-primary", id:"delete-btn" %>
  </div>
  
  <div class="jumbotron" id="users-index-jumbotron">
    <a href="#collapse<%= user.id %>" data-toggle="collapse" class="btn btn-lg btn-primary">編集</a>
    <div id="collapse<%= user.id %>" class="collapse">
      <%= form_with(model: user, url: user_path(user), method: :patch, local: true) do |f| %>
      <%= render partial: 'shared/error_messages', locals: {obj: user} %>
    
       <%= f.label :name, class: "label-form" %>
       <%= f.text_field :name, class:  "form-control"%>
      
       <%= f.label :email, class: "label-form" %>
       <%= f.email_field :email, class:  "form-control"%>
       
       <%= f.label :affiliation, class: "label-form" %>
       <%= f.text_field :affiliation, class:  "form-control"%>
       
       <%= f.label :employee_number, class: "label-form" %>
       <%= f.text_field :employee_number, class:  "form-control"%>
       
       <%= f.label :uid, class: "label-form" %>
       <%= f.text_field :uid, class:  "form-control"%>
      
       <%= f.label :password, class: "label-form" %>
       <%= f.password_field :password, class:  "form-control"%>
       
       <%= f.label :basic_work_time, class: "label-form" %>
       <%= f.time_field :basic_work_time, class:  "form-control"%>
          
       <%= f.label :designated_work_start_time, class: "label-form" %>
       <%= f.time_field :designated_work_start_time, class:  "form-control"%>
  
       <%= f.label :designated_work_end_time, class: "label-form" %>
       <%= f.time_field :designated_work_end_time, class:  "form-control"%>
           
       <%= f.submit "編集する", class: "btn btn-primary btn-block btn-form" %>
      <% end %>
    </div>
  </div>
</ul>

app/views/users/edit.html.erb
<% provide(:title, 'アカウント情報の更新') %>
<% provide(:btn_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
    <p>パスワードを変更しない場合は、空欄のまま更新できます。</p>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:class_text, "基本情報の修正") %>
<% provide(:btn_text, "更新") %>
<h1>基本勤怠の修正</h1>
<h2><%= @user.name %></h2>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <h2>このページは実装されていません。</h2>
  </div>
</div>

app/views/users/edit_overtime_req.js.erb
$("#edit-overtime-req").html("<%= escape_javascript(render 'edit_overtime_req') %>")
$("#edit-overtime-req").modal("show")

app/views/users/index.html.erb
<% provide(:title, "社員一覧") %>

<h1>Z戦士一覧</h1>

<div class="col-md">
  <%= form_tag import_users_path, multipart: true do %>
    <div class="panel pane-default">
      <%= file_field_tag :file, class:"btn btn-default" %>
      <%= submit_tag "CSVをインポート", class:"form_control btn btn-primary", id:"csv-btn" %>
    </div>
  <% end %>
</div>

<div class="col-md-10 col-md-offset-1">
 <%= will_paginate %>
  <ul class="users">
    <%= render @users %>
  </ul>
 <%= will_paginate %>
</div>

app/views/users/index_working_users.html.erb
<% provide(:title, "出動戦士一覧") %>
<h1>出勤中社員一覧</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table table-condensed table-hover" id="table-users">
      <thead>
          <tr>
            <th>社畜番号</th>
            <th>氏名</th>
          </tr>
        </thead>
        <% @working_users.each do |user| %>
          <tr>
            <td><%= user.employee_number %></td>
            <td><%= user.name %></td>
          </tr>
        <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'アカウント作成') %>
<% provide(:btn_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered user-table">
    <tr>
      <td>
        <%= link_to "⇦ ", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        　【<%= l(@first_day, format: :middle) %>】　時間管理表　
        <%= link_to " ⇨", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
        </td>
      <td colspan="2">基本時間：<%= format_basic_info(@user.basic_work_time) %></td>
      <td colspan="2">指定勤務開始時間：<%= format_basic_info(@user.designated_work_start_time) %></td>
      <td colspan="2">指定勤務終了時間：<%= format_basic_info(@user.designated_work_end_time) %></td>
      <td>月初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>名前：<%= @user.name %></td>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>出勤日数：<%= @worked_sum %></td>
      <td>社畜番号</td>
      <td><%= @user.employee_number %></td>
      <td>カードID</td>
      <td><%= @user.uid %></td>
      <td>締め日：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<% if current_user.superior? %>
  <div class="notice-superior">
    <li>【所属長承認申請のお知らせ】</li>    
    <li>【勤怠変更申請のお知らせ】</li>    
    <li>【残業申請のお知らせ】</li>    
  </div>
<% end %>

<div class="btn-users-show">
  　　<%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary", id:"btns" %>
  　　<%= link_to "CSV出力", '#', class: "btn btn-primary", id:"btns" %>
  <ul><%= link_to "勤怠修正ログ (承認済み)", '#', class: "btn btn-primary", id:"btns" %></ul>
</div>

<div>
  <table class="table table-bordered table-condensed table-striped table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="7">【実績】</th>
        <th colspan="5">所定外勤務</th>
      <tr>
        <th colspan="2">出社</th>
        <th rowspan="2">登録</th>
        <th colspan="2">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <% css_class = case $days_of_the_week[day.worked_on.wday]
                       when '土'
                         'text-primary'
                       when '日'
                         'text-danger'
                       end %>
        <tr>
          <td>
            <!-- トリガー:起動指示をする部品 -->
            <%= link_to "残業申請", edit_overtime_req_user_path(@user), remote: true, class:"btn btn-primary" %>
          </td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class=<%= css_class %>>
            <%= $days_of_the_week[day.worked_on.wday] %>
          </td>
          <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%= l day.started_at.floor_to(15.minutes), format: :minute if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to btn_text, user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
            <%= "登録済み" if day.finished_at.present? %>
          </td>
          <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
          <td><%= l day.finished_at.floor_to(15.minutes), format: :minute if day.finished_at.present? %></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes),
                                            day.finished_at.floor_to(15.minutes)) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <td rowspan="2"></td>
        <td colspan="2">累計日数</td>
        <td colspan="5">総勤務時間</td>
        <td>累計在社時間</td>
        <td rowspan="2", colspan="5"></td>
        <td rowspan="2">
           <P><%= "所属長承認" %></p>
            <select class="form-control">
              <option></option>
              <option>上長A</option>
              <option>上長B</option>
            </select>
          　<%= link_to "申請", '#', class:"btn btn-primary" %>
        </td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="5"><%= format_basic_info(@user.basic_work_time).to_f * @worked_sum %></td>
        <td>
          <%= format("%.2f", @total_working_times.to_f) %></td>
      </tr>
    </tfoot>  
  </table>
</div>


<!--モーダル表示-->
<div id="edit-overtime-req" class="modal fade" tabindex="-1" roll="dialog" aria-hidden="true"></div>