config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    collection { post :import }
    member do
      get 'index_working_users'
      post 'index_working_users'
      get 'edit_overtime_req'
      patch 'update_overtime_req'
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
    end
    resources :attendances, only: :update
  end
  
  resources :bases
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" id="header">
  <div class="container">
    <%= link_to "勤怠システムA", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップ", root_path, class:"header-list" %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "社員一覧", users_path, class:"header-list" %></li>
            <li><%= link_to "出勤中一覧", index_working_users_user_path(current_user), class:"header-list" %></li>
            <li><%= link_to "拠点情報の修正", bases_path, class:"header-list" %></li>
            <li><%= link_to "基本勤怠の修正", edit_basic_info_user_path(current_user), class:"header-list" %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "詳細", current_user, class:"h-dropdown-list" %></li>
              <li><%= link_to "設定", edit_user_path(current_user), class:"h-dropdown-list" %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete, class:"h-dropdown-list" %>
              </li>
            </ul>
        <% else %>
        <li><%= link_to "ログイン", login_path, class:"header-list" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_titled(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>